spring:
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
  endpoint:
    health:
      status:
        http-mapping:
          down: 200
      show-details: ALWAYS
  info:
    env:
      enabled: true
    java:
      enabled: true
  health:
    ping:
      enabled: true
    defaults:
      enabled: false
  security:
    enabled: false

info:
  config:
    fritzbox:
      url: ${fritzbox.url}
      switchid: ${fritzbox.switchid}