version: '3.7'

services:
  fe2_smarthome:
    image: odin568/fe2_smarthome:latest
    container_name: fe2_smarthome
    ports:
      - "8082:8080"
    restart: always
    healthcheck:
      test: curl --insecure --fail http://localhost:8080/actuator/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      ## Adjust logging
      #- LOGGING_LEVEL_COM_ODIN568=DEBUG
      #- LOGGING_LEVEL_COM_GITHUB_KAKLAKARIADA_FRITZBOX=DEBUG
      - FRITZBOX_URL=http://fritz.box # better use ip directly
      - FRITZBOX_USERNAME=addUserNameHere
      - FRITZBOX_PASSWORD=addPasswordHere
      - FRITZBOX_SWITCHID=addSwitchIdHere # to find out, enter any number and call the getDevices API to grab the correct switchId
